### ISSUE TITLE
使用初感

### ISSUE THREAD

**Issue by jianghuzai** [chillzhuang/SpringBlade#11]
* 看到文档介绍，好强大，都心动要自己付费了
* 创建第一个demo
    * what？要改启动类的main方法？emmm.....好吧。
    * what？appName要在main方法传进去？这不是应该从application.yml或者bootstrap.yml读取的吗？ emmm....好吧。
* 好奇的进入自定义启动类看看
    * what？activeProfile默认是dev？我不能不设置activeProfile吗？现在的微服务，不同环境的配置都会在配置中心管理了。
    * what？activeProfile不能有多个？为啥要有这个限制？给我个合适的理由？
    * what？isLocalDev就判断一下系统是不是linux系统?我不能在ubuntu使用这个框架开发？
    * what？allow-bean-definition-overriding=true？bean有冲突就说明了有坑，直接覆盖而不是找问题？真粗暴。
    * what？file-extension只能是yml？我为啥不能是properties？
    * what？LogLauncherServiceImpl直接写死日志配置路径？。。。。

我默默地整理了一下凌乱的思路。。。

**Comment by lijunye911** [comment]
非常同意上面这菜逼的说法！！！补充：what？spring.cloud.alibaba.seata.tx-service-group 也要写死？
为什么要不给使用者自主选择权？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？

**Comment by chillzhuang** [comment]
https://gitee.com/smallc/SpringBlade/issues/I1V104
