### ISSUE TITLE
写测试类时，提示找不到占位符'blade.env' 

### ISSUE THREAD

**Issue by die1100** [chillzhuang/SpringBlade#2]
这个测试类该怎么写？

![TIM图片20190614180440](https://user-images.githubusercontent.com/13555654/59501810-e5b8a000-8ece-11e9-9a61-371ee2480a04.png)

我正常运行SpiderApplication没问题，但是写到测试类里就出现找不到blade.env，我哪里写错了吗？

运行报错：
Could not resolve placeholder 'blade.env' in value "classpath:log/logback_${blade.env}.xml"

**Comment by chillzhuang** [comment]
已解决，demo在blade-desk
