### ISSUE TITLE
sql 注入问题

### ISSUE THREAD

**Issue by s-chance** [chillzhuang/SpringBlade#32]
[UserMapper.xml](https://github.com/chillzhuang/SpringBlade/blob/master/blade-service/blade-system/src/main/java/org/springblade/system/mapper/UserMapper.xml)
```xml
<select id="exportUser" resultType="org.springblade.system.excel.UserExcel">
        SELECT id, tenant_id, account, name, real_name, email, phone, birthday, role_id, dept_id, post_id FROM blade_user ${ew.customSqlSegment}
</select>
```
这段sql中使用 `${}` 的方式拼接，是否存在 sql 注入问题？

过去有 [issue](https://github.com/chillzhuang/SpringBlade/issues/28) 已提到过此问题，不过目前未做回复。想了解一下是否已经有其他措施针对此问题进行了处理？

**Comment by s-chance** [comment]
[https://gitee.com/smallc/SpringBlade/issues/IA6MBI?from=project-issue](https://gitee.com/smallc/SpringBlade/issues/IA6MBI?from=project-issue) 已找到回复

**Comment by s-chance** [comment]
> https://gitee.com/smallc/SpringBlade/issues/IA6MBI?from=project-issue 已找到回复

但是如果升级版本的成本较大的话，是否将 `${}` 改为 `#{}` 即可？

**Comment by s-chance** [comment]
不过，为了保险起见以及统一编码，是否将 `${}` 替换为 `#{}` 比较好？

**Comment by sumanrox-work** [comment]
is there a fix commit for this SQL injection?

**Comment by s-chance** [comment]
> is there a fix commit for this SQL injection?

see this [document](https://www.kancloud.cn/smallchill/blade-safety/3234106). 

It seems to use a custom SQL injection filtering class([SqlKeyword.java](https://gitee.com/smallc/blade-tool/blob/master/blade-starter-mybatis/src/main/java/org/springblade/core/mp/support/SqlKeyword.java))  to prevent SQL injection.

If you use code like

```java
QueryWrapper<User> queryWrapper = org.springblade.core.mp.support.Condition.getQueryWrapper(user, User.class);
```

It will call the `SqlKeyword.buildCondition(query, qw);` to filter out some suspicious keywords.

```java
public static <T> QueryWrapper<T> getQueryWrapper(Map<String, Object> query, Map<String, Object> exclude, Class<T> clazz) {
	exclude.forEach((k, v) -> query.remove(k));
	QueryWrapper<T> qw = new QueryWrapper<>();
	qw.setEntity(BeanUtil.newInstance(clazz));
	SqlKeyword.buildCondition(query, qw);
	return qw;
}
```
