### ISSUE TITLE
生成token的Kv类克隆方法，强转错误

### ISSUE THREAD

**Issue by LesliePie** [chillzhuang/SpringBlade#4]
该类继承 LinkedCaseInsensitiveMap
public Kv clone() {
        return (Kv)super.clone();
    }

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：jun wang <notifications@github.com>
发送时间：2019-12-02 12:25
主题：[chillzhuang/SpringBlade] 生成token的Kv类克隆方法，强转错误 (#4)
收件人："chillzhuang/SpringBlade"<SpringBlade@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

该类继承 LinkedCaseInsensitiveMap
public Kv clone() {
return (Kv)super.clone();
}

**Comment by ChunMengLu** [comment]
已修复：

https://github.com/chillzhuang/blade-tool/blob/master/blade-core-tool/src/main/java/org/springblade/core/tool/support/Kv.java#L200
