### ISSUE TITLE
库存减少方法是否会存在竞争条件

### ISSUE THREAD

**Issue by a413528002** [chillzhuang/SpringBlade#6]
下面是库存减少的代码片段，出自org.springblade.seata.storage.service.impl.StorageServiceImpl

 
@Override
	@Transactional(rollbackFor = Exception.class)
	public int deduct(String commodityCode, int count) {
		Storage storage = baseMapper.selectOne(Wrappers.<Storage>query().lambda().eq(Storage::getCommodityCode, commodityCode));
		if (storage.getCount() < count) {
			throw new RuntimeException("超过库存数，扣除失败！");
		}
		storage.setCount(storage.getCount() - count);
		return baseMapper.updateById(storage);
	}

**Comment by chillzhuang** [comment]
这个是基于seata官方源码做了小部分修改，仅仅是为了展示seata的demo，并没有加入业务场景。否则会写的非常复杂不利于刚接触的同学学习

**Comment by zlf2002171** [comment]
unsubscribe
2020-05-18 

zlf2002171 



发件人：Chill <notifications@github.com>
发送时间：2020-04-13 09:24
主题：Re: [chillzhuang/SpringBlade] 库存减少方法是否会存在竞争条件 (#6)
收件人："chillzhuang/SpringBlade"<SpringBlade@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

Closed #6.

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：a413528002 <notifications@github.com>
发送时间：2020-04-13 00:13
主题：[chillzhuang/SpringBlade] 库存减少方法是否会存在竞争条件 (#6)
收件人："chillzhuang/SpringBlade"<SpringBlade@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

下面是库存减少的代码片段，出自org.springblade.seata.storage.service.impl.StorageServiceImpl
@override
@transactional(rollbackFor = Exception.class)
public int deduct(String commodityCode, int count) {
Storage storage = baseMapper.selectOne(Wrappers.query().lambda().eq(Storage::getCommodityCode, commodityCode));
if (storage.getCount() < count) {
throw new RuntimeException("超过库存数，扣除失败！");
}
storage.setCount(storage.getCount() - count);
return baseMapper.updateById(storage);
}
